import {
  SCHEMA_VERSION,
  CREATE_TABLE_FILES,
  CREATE_INDEX_FILES_DOWNLOADED,
  CREATE_TABLE_ENTITY_FILES,
  CREATE_INDEX_ENTITY_FILES,
  CREATE_TABLE_TRACKING_POLICY_CACHE,
  CREATE_TABLE_GPS_POINTS_QUEUE,
  CREATE_INDEX_GPS_POINTS_QUEUE_DEVICE_STATUS,
  CREATE_TABLE_GPS_SYNC_STATE,
} from './schema';

export type Migration = {
  version: number;
  statements: string[];
};

export const MIGRATIONS: Migration[] = [
  {
    version: 1,
    statements: [
      CREATE_TABLE_FILES,
      CREATE_INDEX_FILES_DOWNLOADED,
      CREATE_TABLE_ENTITY_FILES,
      CREATE_INDEX_ENTITY_FILES,
    ],
  },
  {
    version: 2,
    statements: [
      CREATE_TABLE_TRACKING_POLICY_CACHE,
      CREATE_TABLE_GPS_POINTS_QUEUE,
      CREATE_INDEX_GPS_POINTS_QUEUE_DEVICE_STATUS,
      CREATE_TABLE_GPS_SYNC_STATE,
    ],
  },
];

export { SCHEMA_VERSION };
